version: '3.7'

volumes:
    mongodata:

services:
    mongo:
        image: 'mongo:latest'
        restart: always
        ports:
            - '27017:27017'
        volumes:
            - 'mongodata:/data/db'
    redis:
        image: 'redis:latest'
        restart: always
        ports:
            - '6379:6379'
        volumes:
            - './services/data/cache:/data'
    dynamodb:
        image: 'amazon/dynamodb-local:latest'
        restart: always
        ports:
            - '8000:9125'
